version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "action version"
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "@admin"