name: Push Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  push:
    name: "Push"
    steps:
    -
      name: Checkout Project
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CI_PAT }}
        fetch-depth: 0
    - 
        name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    -
        name: Push latest
        run: |
          version=$(cut -d. -f1 <<<"${{ steps.vars.outputs.tag }}")
          git config --local user.name "skafld"
          git config --local user.email "skafld@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.CI_PAT }}@github.com/${{ github.repository }}
          git tag -f latest
          git tag -f $version
          git push -f origin latest
          git push -f origin $version
