name: Maven check
on:
  workflow_call:
    inputs:
      java_version:
        type: string
        default: '17'
        required: false
        description: Java version
      module_version:
        type: string
        default: "1.0.0"
        required: true
        description: Module version
      maven_repository:
        type: string
        default: "https://maven.pkg.github.com/skafld/github-actions"
        required: true
        description: Maven repository
      runner_tags:
        type: string
        required: false
        
        description: GitHub runner tags
    secrets:
      CI_PAT:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  maven-build-and-deploy:
    name: "maven-build-and-deploy"
    runs-on: ["ubuntu-20.04"]
    steps:
      -
        name: Checkout Project
        uses: actions/checkout@v1
        with:
          token: ${{ secrets.CI_PAT }}
      -
        name: Setup java
        uses: actions/setup-java@v3
        with:
          cache: maven
          distribution: adopt
          java-version: ${{ inputs.java_version }}
          server-id: github
          server-username: GITHUB_USER
          server-password: GITHUB_TOKEN


      -
        name: Generate module
        run: make maven/build
        env:
          GITHUB_USER: skafld
          GITHUB_TOKEN: ${{ secrets.CI_PAT }}
      -
        name: Deploy client
        run: |
          mvn -ntp versions:set -DnewVersion=${{inputs.module_version}} -DprocessAllModules
          mvn -ntp deploy -DaltDeploymentRepository=github::default::${{inputs.maven_repository}} -DskipTests=true -Djacoco.skip=true

        env:
          GITHUB_USER: skafld
          GITHUB_TOKEN: ${{ secrets.CI_PAT }}
