name: Maven check
on:
  workflow_call:
    inputs:
      node_version:
        type: string
        default: '12.x'
        required: false
        description: NodeJS version
      runner_tags:
        type: string
        required: false
        
        description: GitHub runner tags
    secrets:
      CI_PAT:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  npm-build-and-deploy:
    runs-on: ["ubuntu-20.04"]
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
          registry-url: ${{inputs.node_version}}
          # Defaults to the user or organization that owns the workflow file
          scope: '@skafld'
      -
        name: Build and Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CI_PAT }}
        run: |
          npm install
          npm run build
          npm --loglevel info publish
      -
        name: Clean state
        run: |
          git checkout ./