name: Pyspark check
on:
  workflow_call:
    inputs:
      python_version:
        type: string
        default: '3.8'
        required: false
        description: Python version
      poetry_version:
        type: string
        default: '1.1.15'
        required: false
        description: poetry version

jobs:
  verify:
    name: "Verify"
    runs-on: ["ubuntu-20.04"]
    steps:
    -
      name: Checkout Project
      uses: actions/checkout@v3
      with:
        submodules: true
    -
      name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python_version }}
    -
      name: Install poetry
      run: |
        pip install --disable-pip-version-check "poetry==${{ inputs.poetry_version }}"
    -
      name: Install dependencies
      run: make pyspark/configure
    -
      name: Run checkstyle
      run: make pyspark/checkstyle
    -
      name: Run tests
      run: make pyspark/test

