name: Scheduler trigger dag copy
on:
  workflow_call:
    inputs:
      dag_name:
        type: string
        required: true
        description: "Dag name (Eq: etlstandards)"
      env_name:
        type: string
        required: false
        default: load
        description: "Env name (load | production)"
      dag_config_name:
        type: string
        default: ''
        required: false
        description: "Config to copy (Eq: SPARK_IMAGE_TAG)"
      dag_config_from_env:
        type: string
        required: true
        default: 'development'
        description: "Env name to copy the configs from (Eq: development)"
      runner_tags:
        type: string
        required: false
        
        description: GitHub runner tags
    secrets:
      CI_PAT:
        required: true

jobs:
  dispatch:
    name: "Dispatch"
    runs-on: ["ubuntu-20.04"]
    steps:
    -
      id: dispatch
      uses: octokit/request-action@v2.x
      env:
        GITHUB_TOKEN: ${{ secrets.CI_PAT }}
      with:
        route: POST /repos/:owner/:repository/actions/workflows/:workflow/dispatches
        mediaType: |
          format: application/vnd.github.v3+json
        owner: skafld
        repository: scheduler
        workflow: update-dag.yaml
        ref: main
        inputs: |
          env_name: "${{ inputs.env_name }}"
          dag_name: "${{ inputs.dag_name }}"
          dag_config_name: "${{ inputs.dag_config_name }}"
          dag_config_from_env: "${{ inputs.dag_config_from_env }}"
          commit_message: "Triggered by https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
