name: Terraform check
on:
  workflow_call:
    inputs:
      default_env:
        type: string
        required: false
        default: development
        description: Default env name
      runner_tags:
        type: string
        required: false
        
        description: GitHub runner tags
    secrets:
      CI_PAT:
        required: true
      ENVIRONMENT_NAMES:
        required: false
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ASSUMABLE_ROLES_MAP:
        required: true

jobs:
  env:
    name: Env
    runs-on: ["ubuntu-20.04"]
    outputs:
      names: ${{ steps.env.outputs.names }}

    steps:
    -
      name: Checkout Project
      uses: actions/checkout@v4
    -
      id: env
      run: |
        echo "names=$(github-env-names -t terraform -o json || echo '[]')" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.CI_PAT }}

  validate:
    name: "Validate"
    runs-on: ["ubuntu-20.04"]
    steps:
    -
      name: Configure git override
      run: |
        git config --global url."https://oauth2:${{ secrets.CI_PAT }}@github.com".insteadOf ssh://git@github.com
    -
      name: Checkout Project
      uses: actions/checkout@v4
    -
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    -
      name: Terraform init
      run: make ENV=${{ inputs.default_env }} terraform/init
    -
      name: Terraform validate
      run: make ENV=${{ inputs.default_env }} terraform/validate

  plan:
    name: "Plan"
    needs: [env, validate]
    if: ${{ needs.env.outputs.names }}
    runs-on: ["ubuntu-20.04"]
    concurrency: terraform-${{ matrix.env }}
    env:
      GITHUB_TOKEN: ${{ secrets.CI_PAT }}
    strategy:
      fail-fast: false
      matrix:
        env: ${{ fromJson(needs.env.outputs.names) }}

    steps:
    -
      name: Configure git override
      run: |
        git config --global url."https://oauth2:${{ secrets.CI_PAT }}@github.com".insteadOf ssh://git@github.com
    -
      name: Checkout Project
      uses: actions/checkout@v4
    -
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    -
      name: Create aws profile
      run: aws configure set region $AWS_REGION --profile ${{ matrix.env }}
    -
      name: Assume AWS Role
      uses: aws-actions/configure-aws-credentials@v2
      if: ${{ fromJson(env.AWS_ASSUMABLE_ROLES_MAP)[matrix.env] }}
      with:
        aws-region: us-east-1
        role-duration-seconds: 1800
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: ${{ fromJson(env.AWS_ASSUMABLE_ROLES_MAP)[matrix.env] }}
      env:
        AWS_ASSUMABLE_ROLES_MAP: ${{ secrets.AWS_ASSUMABLE_ROLES_MAP }}
    -
      name: Terraform init
      run: make ENV=${{ matrix.env }} terraform/init
    -
      name: Terraform plan
      run: make ENV=${{ matrix.env }} TF_CMD_ARGS='-lock=false' terraform/plan
