name: Trigger Workflow
on:
  workflow_call:
    inputs:
      ref:
        description: Git Ref
        required: true
        type: string
      workflow:
        description: 'Workflow name'
        required: true
        type: string
      inputs:
        description: 'Workflow inputs'
        required: true
        type: string
      runner_tags:
        type: string
        required: false
        
        description: GitHub runner tags
    secrets:
      CI_PAT:
        required: true

jobs:
  dispatch:
    runs-on: ${{ fromJson(inputs.runner_tags) }}
    name: "Dispatch (${{ inputs.workflow }})"
    steps:
      -
        name: Dispatch workflow
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/actions/workflows/:workflow/dispatches
          mediaType: |
            format: application/vnd.github.v3+json
          workflow: ${{ inputs.workflow }}.yaml
          inputs: ${{ inputs.inputs }}
          ref: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.CI_PAT }}
